### PR TITLE
APP-2335 Remove reserved fields for unused EndUserService protos

### PR DESCRIPTION
**Pull request by ethanlook**
I added the reserved fields in https://github.com/viamrobotics/api/pull/372 but the protos are unused, so it's safe to not reserve them. It was easier to open a new PR than to modify the previous one.

@stevebriskin for the force merge. (Apologies, this has been more tumultuous than expected.)

### CODE REVIEW

**Review by ohEmily — APPROVED** [review]
LGTM. Sorry for causing this big mess!!!

**Comment by ethanlook** [comment]
> LGTM. Sorry for causing this big mess!!!

No worries at all! It happens! Glad we can get into a good state.

**Comment by ethanlook** [comment]
@stevebriskin ready for force merge

**Review by mcous — APPROVED** [review]
🦑

**Review by stevebriskin — APPROVED** [review]

**Pull request merged**
