### PR TITLE
APP-2536 - Cleanup unused orgid fields in module protos

### PR DESCRIPTION
**Pull request by zaporter-work**
Ticket : https://viam.atlassian.net/browse/APP-2536

Tested against https://github.com/viamrobotics/app/pull/2282
- No linting errors
- Make up succeeds
- No test failures (in the non-scheduler tests)

Will request review 1 week after https://github.com/viamrobotics/app/pull/2282 is merged to avoid breaking others who are using older branches off app.

Will re-test pre-merging.

### CODE REVIEW

**Comment by zaporter-work** [comment]
Retested against app@head. No lint or test failures (on my machine).

**Review by michaellee1019 — APPROVED** [review]
LGTM!

**Comment by zaporter-work** [comment]
Do either of you @DTCurrie  or @stevebriskin think that this requires a scope? These fields were never in the original scope and we thought they were needed but they never ended up being used.

**Comment by DTCurrie** [comment]
> Do either of you @DTCurrie or @stevebriskin think that this requires a scope? These fields were never in the original scope and we thought they were needed but they never ended up being used.

If this was pre-release and never used I am ok with no scope doc, but I think @stevebriskin will have to make the final call since he has the power to merge.

**Comment by michaellee1019** [comment]
> I am ok with no scope doc

These changes were already included in a email thread for the updated scope (amongst many other things). It was sent a few weeks ago but didn't do the PR until now.

**Pull request merged**
