### PR TITLE
Added proto messages for adding a role to and removing role from api key

### PR DESCRIPTION
**Pull request by Oabraham1**
I will be adding the `api_key` field to the Authorization type definition to enable us more easily support `AddRole` and `RemoveRole` for api keys. Adding the API Key field to the authorization field enables us perform necessary lookups for during authorization.

### CODE REVIEW

**Comment by Oabraham1** [comment]
Thinking about this even more and I don't think we even need to add the API Key to the authorization since we could just pass in the api key id as the identityID and use that to perform necessary lookups. Let me know what you think @ehhong @piokasar

**Comment by ehhong** [comment]
> Thinking about this even more and I don't think we even need to add the API Key to the authorization since we could just pass in the api key id as the identityID and use that to perform necessary lookups.

I agree with this!

**Comment by Oabraham1** [comment]
> > Thinking about this even more and I don't think we even need to add the API Key to the authorization since we could just pass in the api key id as the identityID and use that to perform necessary lookups.
> 
> I agree with this!

Thanks Emily, gonna work on refactoring the code to test out this hypotheses.

**Comment by Oabraham1** [comment]
Closing this PR since we're not using api key in the authorization request anymore

**Pull request closed without merging**
