### PR TITLE
DATA-2006 - Remove filter from SubmitTrainingJobRequest in API

### PR DESCRIPTION
**Pull request by tahiyasalam**
I cross-referenced this PR against both https://github.com/viamrobotics/app/pull/3010 and https://github.com/viamrobotics/rdk/pull/3267, where tests in all scenarios and there was no reference to the `GetFilter` field. Once merged, I will double pull into `app` and complete the last change which is removing the `filter: undefined` field from the FE

### CODE REVIEW

**Review by agreenb — APPROVED** [review]
LGTM, can get approval from Simone or Steve and make sure to merge both this and the app update before tomorrow's deployment.

**Comment by tahiyasalam** [comment]
@Simberific would you mind manually merging? This is based on [this scope doc](https://docs.google.com/document/d/1D6TGiQ9n1qip1jW2O_dg5ahNv__1O_pZztqwT3hF7fI/edit?usp=sharing), where we decided we would disallow training on data by filter and only support training on data in dataset.

**Comment by Simberific** [comment]
Hi Tahiya - so sorry I missed this. Do you still need assistance?

**Comment by agreenb** [comment]
Thank you!

**Pull request merged**
