### PR TITLE
[RSDK-1597] Update package proto

### PR DESCRIPTION
**Pull request by agreenb**
Update to a `packages` package and directory.

### CODE REVIEW

**Comment by agreenb** [comment]
@stevebriskin Attempted to add the linter into our toolkit, but wasn't quickly able to get it working. I assume the java issue is with the namespace rather than the RPC service, and there's no requirement for the directory/package to match the service name. 

Think PackageService is still preferable to PackagesService.

**Review by stevebriskin — APPROVED** [review]

**Comment by agreenb** [comment]
+ @sbal13 for the gateway annotations

**Review by sbal13 — APPROVED** [review]
🔥

**Review by tahiyasalam — APPROVED** [review]

**Review by tahiyasalam — COMMENTED** [review]
Quick check: under app and gen/js/app, we have both package/ and packages/

Maybe remove and run `make/dist-buf` again?

**Comment by agreenb** [comment]
@stevebriskin This is a breaking change since removes the old "package.proto" file, so good to force merge!

Double checking again that the issue was the namespace and not `message Package`, which is currently still present.

**Comment by stevebriskin** [comment]
Yes, the issue was with the package namespace, not the service name -- `package viam.app.package.v1;`

**Comment by agreenb** [comment]
@tahiyasalam Great catch, wiped gen/js clean locally to get it working.

@stevebriskin now ready :)

**Pull request merged**
