### PR TITLE
RSDK- 1851 Backend implementation for removing Interaction Spaces from WorldState

### PR DESCRIPTION
**Pull request by nfranczak**

### CODE REVIEW

**Comment by nfranczak** [comment]
this is a breaking change. Will require manual merge.
Will request manual merge on completion of: https://viam.atlassian.net/browse/RSDK-1889

**Review by biotinker — APPROVED** [review]
This LGTM

**Review by spieswl — APPROVED** [review]
LGTM

**Review by raybjork — APPROVED** [review]

**Review by cheukt — APPROVED** [review]

**Comment by nfranczak** [comment]
@edaniels  requesting manual merge, as this is a breaking change.

**Pull request merged**
