### PR TITLE
APP-2335 Remove user_id from EndUser RPC requests

### PR DESCRIPTION
**Pull request by ethanlook**
See the discussion for why to remove the field: https://github.com/viamrobotics/app/pull/2546

This marks the `user_id` field as reserved. By doing this, the field will no longer be required in requests for the RPCs but is safely marked as reserved to prevent future reuse.

See [reserved fields](https://protobuf.dev/programming-guides/proto3/#fieldreserved) and [consequences of reusing field numbers](https://protobuf.dev/programming-guides/proto3/#consequences) for more info.

### CODE REVIEW

**Review by mcous — APPROVED** [review]
LGTM

**Comment by ethanlook** [comment]
Added @stevebriskin for merging the breaking change.

**Comment by stevebriskin** [comment]
> Added @stevebriskin for merging the breaking change.



> See the discussion for why to remove the field: [viamrobotics/app#2546](https://github.com/viamrobotics/app/pull/2546)
> 
> This marks the `user_id` field as reserved. By doing this, the field will no longer be required in requests for the RPCs but is safely marked as reserved to prevent future reuse.
> 
> See [reserved fields](https://protobuf.dev/programming-guides/proto3/#fieldreserved) and [consequences of reusing field numbers](https://protobuf.dev/programming-guides/proto3/#consequences) for more info.

Should just remove the field. It was just introduced and no one is using it.

**Comment by ethanlook** [comment]
> Should just remove the field. It was just introduced and no one is using it.

That's what I did - the failing check is because the field was deleted. The `reserved` keyword is not causing the check to fail. AFAICT (based on [previous](https://github.com/viamrobotics/api/pull/363) [examples](https://github.com/viamrobotics/api/pull/359)), a force merge is needed when deleting fields.

**Comment by ohEmily** [comment]
@ethanlook not sure I understand your response to Steve's comment. It looks like the field is now marked as reversed [here](https://github.com/viamrobotics/api/pull/372/files#diff-a9b71a46ce21ecb89e78164be49f980caadad4344c1116b519e8fc41dafd5d7eR28-R30).

**Comment by ethanlook** [comment]
> @ethanlook not sure I understand your response to Steve's comment. It looks like the field is now marked as reversed [here](https://github.com/viamrobotics/api/pull/372/files#diff-a9b71a46ce21ecb89e78164be49f980caadad4344c1116b519e8fc41dafd5d7eR28-R30).

You're correct, I misunderstood what Steve was saying and we followed up offline. The plan is to:

1) Force merge this PR
2) Open a follow-up PR to remove the reserved fields.

**Comment by ohEmily** [comment]
Ah ok thank you! Also lol at my own typo, "reserved" not "reversed" 🙃

**Pull request merged**
