### PR TITLE
[DATA-1059] Set up fake data service server to test trainingJobManager

### PR DESCRIPTION
**Pull request by tahiyasalam**
The mock file was created using the command:
`mockgen -source=app/data/v1/data_grpc.pb.go -destination=app/mock_v1/mock_data_grpc.pb.go`

### CODE REVIEW

**Comment by agreenb** [comment]
Really cool to see the use of mockgen! Double checking if you had to manually add `v1.UnimplementedDataServiceServer` and, if so, there's a follow-up with other folks who didn't have to manually edit the files.

**Comment by tahiyasalam** [comment]
@agreenb I did manually add it, based on [this](https://github.com/grpc/grpc-go/releases/tag/cmd%2Fprotoc-gen-go-grpc%2Fv1.0.0) and conversations with Adam, seems like it is okay/necessary to add that in.

**Comment by agreenb** [comment]
Great, only request is that at the top of the file to add something like:
``` // DO NOT EDIT, except for manually adding v1.UnimplementedDataServiceServer to MockDataServiceServer struct ``` 

That'll make it clear if these files are autogenerated/overwritten after changes to data.proto that the PR owner needs to add that back in.

**Review by agreenb — APPROVED** [review]
LGTM once adding that comment in at the top!

**Comment by AaronCasas** [comment]
+1 to @agreenb, and would recommend adding a link for context to so future readers know why that was needed!

**Review by AaronCasas — APPROVED** [review]

**Pull request closed without merging**
