### PR TITLE
RSDK-4289 remove MoveSingleComponent from motion service

### PR DESCRIPTION
**Pull request by raybjork**

### CODE REVIEW

**Comment by raybjork** [comment]
@Otterverse we will need to manually merge this, can you help with that?

**Comment by Otterverse** [comment]
> @Otterverse we will need to manually merge this, can you help with that?

Bug me on slack about this. I want to confirm that it's still in a "good to go" state before I merge.

**Comment by Otterverse** [comment]
> > @Otterverse we will need to manually merge this, can you help with that?
> 
> Bug me on slack about this. I want to confirm that it's still in a "good to go" state before I merge.

Actually, other merges have gone in since this built protos. You may need to rebase and retrigger the build process here, or it'll lose the newer changes. I'm gonna go ahead and remove protos-compiled label.

**Review by Otterverse — APPROVED** [review]
Approval to restart proto workflow.

**Pull request merged**
